micronaut:
  application:
    name: Hello Micronaut
  http:
    services:
      fruity:
        url: http://www.fruityvice.com



hello-mn:
  gretting: "Bonjour"



endpoints:
  all:
    sensitive: false
  refresh:
    enabled: true


datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    packages-to-scan:
      - 'hello.mn.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
          import_files: import.sql
        show_sql: true